version: 0.2

phases:
  pre_build:
    commands:
      - GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws/o6o7z4z0
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:latest .
      - echo ${GIT_COMMIT_HASH}   
      - docker tag $IMAGE_REPO_NAME:latest ${ECR_REPOSITORY}:${GIT_COMMIT_HASH}   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY}:${GIT_COMMIT_HASH}
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME public.ecr.aws/o6o7z4z0/storeabc:${GIT_COMMIT_HASH} > imagedefinition.json
      - cat imagedefinition.json
artifacts:
  files: imagedefinition.json
