version: '3.7'
services:
  app:
    image: storeabc
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: storeabc
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      #- .:/var/www/html (only use in local enviroment)
      - /home/mymy/practice-Docker/storeabc/data/img:/var/www/html/storage/app/public

  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - REDIS_CLIENT=predis
    volumes:
      - /home/mymy/practice-Docker/storeabc/data/redis:/data

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/mymy/practice-Docker/storeabc/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=storeabcc
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      
